#[cfg(feature = "python")]
pub mod data;
#[cfg(feature = "python")]
pub mod py_algorithm;
#[cfg(feature = "python")]
pub mod python;
#[cfg(feature = "python")]
pub mod schemas;
#[cfg(feature = "python")]
pub mod statistics;
