name: Publish

on:
  push:
    branches: 'master'

jobs:
  publish:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            manylinux: 2014
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}

    env:
      # Initialize with empty strings so VS Code knows they exist
      AUTHORS: ""
      VERSION: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Find publish metadata
        run: |
          python - <<EOF
          import json, subprocess, os
          metadata = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version=1", "--no-deps"]))
          package_data = metadata["packages"][0]
          with open(os.environ["GITHUB_ENV"], "a") as f:
            f.write(f"AUTHORS={', '.join(package_data['authors'])}\n")
            f.write(f"VERSION={package_data['version']}\n")
          EOF

      - name: Build wheels
        uses: PyO3/maturin-action@v1.50.1
        with:
          command: build
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          args: >
            --release
            --locked
            --authors "${{ env.AUTHORS }}"
            --version "${{ env.VERSION }}"
            --compatibility pypi

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: wheels-${{ matrix.target }}
      #     path: target/wheels/

      # - twine upload target/wheels/*.whl
      # - cargo publish
